version: '3.8'

services:
  postgres:
    container_name: manage-cars-pg
    image: postgres
    ports:
      - 5432:5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=manage-cars-db
      - PGDATA=/data/postgres
    volumes:
      - /data/pg:/data/postgres